### ISSUE TITLE
Error - Status Code 429 SQLSTATE HV000

### ISSUE THREAD

**Issue by Lachlan-White** [turbot/steampipe-plugin-openai#12]
**Describe the bug**
Error occurs each and everytime a call is made to the openai_completion table.

**Steampipe version (`steampipe -v`)**
v0.20.10

**Plugin version (`steampipe plugin list`)**
OpenAI Plugin Version - 0.1.0

**To reproduce**
`SELECT
    openai_completion
FROM
    openai_completion
WHERE
    prompt = 'Hello World';
`

**Expected behavior**
A return message from the openai api.

**Comment by e-gineer** [comment]
429 implies that you are being rate limited by the OpenAI service?

Was it working and then stopped? Or are you using this as part of a join with many rows?

**Comment by Lachlan-White** [comment]
Hey @e-gineer hasn't worked at any stage, just `429`'s on a single first query. Will be attempting to execute on a different machine with another new token today.

**Comment by graza-io** [comment]
Closing as no response received; please feel free to re-open if you have any additional feedback/input.
