### ISSUE TITLE
Your openAI secret key is published

### ISSUE THREAD

**Issue by oelmekki** [turbot/steampipe-plugin-openai#5]
Hi,

Just a fair warning that you've published your API key:

https://github.com/turbot/steampipe-plugin-openai/blob/576d533d878617fba1aef64728ebf1afd85445cf/config/openai.spc#L5

 If you have a a paying account on openAI's api and this key is still valid, it may be used to access the api while billing you. You should probably deactivate this key in openAI's dashboard and remove it from your code, using instead an environment variable or similar.

**Comment by cbruno10** [comment]
Hey @oelmekki , thanks for letting us know!

The API key we had in our config/example docs was an invalid API key, but it's definitely alarming and can also trigger GitHub's secret detection, so we've updated it in https://github.com/turbot/steampipe-plugin-openai/commit/c3b92a5fe309fa4fc9eb462f85b82c094e81057c.
